const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const url=process.env.APP_URL||require('node:url').pathToFileURL(path.resolve(__dirname,'../index.html')).href;
(async()=>{const b=await chromium.launch({headless:true,...(process.env.CHROME_CHANNEL?{channel:process.env.CHROME_CHANNEL}:{})});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForSelector('.tabs');
const result=await p.evaluate(()=>{const sci=STD.filter(r=>r.subj==='과학'),target=sci.find(r=>r.c==='[6과15-04]');return {version:APP_VERSION,count:sci.length,units:new Set(sci.map(r=>r.a)).size,wrong:sci.filter(r=>domName(r)!==DOMAIN_REPAIRS.scienceUnits[r.a]).map(r=>r.c),target:domName(target),idea:domOf(target).idea,content:contentAllOf(target),badAuto:STD.filter(r=>domainEvidence.get(r.c).kind==='suggested'&&domName(r)).map(r=>r.c)};});
assert.equal(result.version,'2.1.2');assert.equal(result.target,'운동과 에너지');assert.equal(result.units,32);assert.deepEqual(result.wrong,[]);assert.deepEqual(result.badAuto,[]);assert(result.idea.some(x=>x.includes('전하와 전류')));assert(result.content['지식·이해'].includes('속력'));assert(result.content['지식·이해'].includes('전기 안전'));assert.equal(result.content['과정·기능'].length,6);assert(result.content['과정·기능'][4].endsWith('적용⋅설명하기'));
// Reproduce old saves: stale full basket + newer explicit empty selection.
await p.evaluate(()=>{localStorage.setItem('cart2022',JSON.stringify(STD.map(r=>r.c)));localStorage.setItem('review-cart2022-v1','[]');});await p.reload();await p.waitForSelector('.tabs');assert.equal(await p.evaluate(()=>S.cart.size),0);
await p.evaluate(()=>{S.q='';S.bands.clear();S.subjs.clear();S.areas.clear();render();});await p.locator('#btnAll').click();assert.equal(await p.evaluate(()=>S.cart.size),611);await p.locator('#btnAll').click();assert.equal(await p.evaluate(()=>S.cart.size),0);await p.reload();await p.waitForSelector('.tabs');assert.equal(await p.evaluate(()=>S.cart.size),0);
assert.equal(await p.evaluate(()=>{let n=0;const old=download;download=()=>n++;try{for(const id of ['cartCsv','cartPlan','cartMd','cartDoc'])document.getElementById(id).onclick();}finally{download=old;}return n;}),0);
// Partial selection: each real download must contain only the selected standard.
await p.evaluate(()=>{S.cart.add('[6과15-04]');saveCart();});for(const id of ['cartCsv','cartPlan','cartMd','cartDoc']){const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#'+id).click()]);const txt=fs.readFileSync(await dl.path(),'utf8');assert(txt.includes('[6과15-04]'));assert(!txt.includes('[6과15-01]'));assert(dl.suggestedFilename().includes('_1건.'));}
await p.reload();await p.waitForSelector('.tabs');assert.deepEqual(await p.evaluate(()=>[...S.cart]),['[6과15-04]']);
// Displayed fallback results and select-all must match.
assert(await p.evaluate(()=>{S.q='6과15-04';S.bands=new Set([0]);S.subjs.clear();S.areas.clear();render();const listed=listedRows().map(r=>r.c);return listed.includes('[6과15-04]')&&listed.length===document.querySelectorAll('[data-cart-code]').length;}));
await p.evaluate(()=>{S.cart.clear();saveCart();DOMPICK['[6과15-04]']='';localStorage.setItem('dompick2022',JSON.stringify(DOMPICK));});await p.reload();await p.waitForSelector('.tabs');assert.equal(await p.evaluate(()=>domName(STD.find(r=>r.c==='[6과15-04]'))),null);assert.deepEqual(errors,[]);
const out={result:'PASS',version:result.version,scienceStandards:result.count,scienceUnits:result.units,checks:['science mapping and repaired merged cells','unreviewed guesses stay unassigned','empty legacy selection migration','select all / deselect all / reload','zero selection blocks four download formats','one selection produces four actual downloads','partial selection persistence','search fallback selection matches visible rows','explicit teacher deferral survives reload','no page errors']};fs.writeFileSync(path.join(__dirname,'selection-domain-verification.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out));}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
