/* v2: deterministic, inspectable composition. Official strings are never rewritten. */
const APP_VERSION='2.1.1',DESIGN_RULES=__DESIGN_RULES__,SOURCE_INDEX=__SOURCE_INDEX__;
openHelp=function(){const body=$('#dlgBody');body.innerHTML='';$('#dlgTitle').textContent='수업 설계 도우미 v'+APP_VERSION;for(const [title,text] of [['공식 자료 살펴보기','성취기준 코드·원문을 복사하고 공식 문서의 PDF 위치를 확인합니다. 원문 표기와 설계 제안은 구분합니다.'],['교사의 생각 구체화하기','마지막 탐구 설계 탭에서 QFT 단계와 교과·수행별 도움자료를 살펴보세요. MD를 내려받아 교과서 자료와 교사의 생각을 적고, AI와 대화하며 PPT 얼개·학습지로 발전시킬 수 있습니다.'],['SUCCESS 모델로 설계','탐구 설계 탭의 ‘SUCCESS 모델로 설계’에서 S·U·CC·E·SS 다섯 단계와 연결된 사회정서역량을 살펴보세요. 한 차시 수업 모형과 프로젝트(PBL)를 바꿔 볼 수 있으며, SUCCESS 설계 MD를 내려받아 AI와 대화하며 설계합니다.'],['선택과 저장','바구니는 다시 눌러 해제할 수 있습니다. 교사의 영역 선택과 피드백은 이 브라우저에 보관하며, 다른 기기에서 사용할 내용은 MD·Word·CSV로 저장하세요.'],['연결을 해석할 때','연관 점수는 문서의 단어 유사도이며 교육적 적합성 확률이 아닙니다. 내용 체계 연결 제안은 공통 단어를 근거로 하며 공식 대응표가 아닙니다.'],['사용량','13개 교과 관점과 7개 수행 규칙, 승인 사례 10개를 재사용합니다. 앱 실행·검색·내보내기에는 생성형 AI 호출이 없습니다.']]){body.appendChild(el('h4',null,title));body.appendChild(el('p',null,text));}if(!$('#dlg').open)$('#dlg').showModal();};
const TEXT_REPAIRS=__TEXT_REPAIRS__;
const originalBootV2=boot;boot=function(data){const copy={...data,std:data.std.map(r=>({...r,...(TEXT_REPAIRS[r.c]?.fields||{})}))};originalBootV2(copy);};
const designCache=new Map(),domainEvidence=new Map();
const baseBuildIndex=buildIndex;
function domainRanking(r){const subj=SUBJ[r.s],list=DOM[subj]||[],exact=list.find(d=>d.name===r.a);if(exact)return {name:exact.name,kind:'name',candidates:[]};
 const own=r.a+' '+r.t+' '+(r.hae||''),ownTokens=new Set(tokens(own));
 const ranks=list.map(d=>{const rows=Object.values(d.content||{}).flatMap(c=>c[BANDS[r.b]]||[]),text=d.name+' '+rows.join(' '),hits=[...new Set(tokens(text))].filter(t=>ownTokens.has(t)&&t.length>1);return {name:d.name,hits,score:hits.reduce((v,t)=>v+(own.includes(t)?t.length:1),0)};}).sort((a,b)=>b.score-a.score);
 if(r.c===REVIEW_CODE)return {name:'지리 인식',kind:'reviewed',candidates:ranks};
 const first=ranks[0],second=ranks[1];return {name:first&&first.score>=4&&(!second||first.score-second.score>=2)?first.name:null,kind:'suggested',candidates:ranks.slice(0,3)};
}
buildIndex=function(){STD.forEach(r=>{const ev=domainRanking(r);domainEvidence.set(r.c,ev);r.dom=ev.name;r.domGuess=ev.kind==='suggested';r.domCand=ev.candidates.map(x=>x.name);});baseBuildIndex();};
function designFor(r){const key=r.c+'|'+domName(r);if(designCache.has(key))return designCache.get(key);const pilot=pilotOf(r),subj=SUBJ[r.s],profile=DESIGN_RULES.subjects[subj],action=DESIGN_RULES.actions.find(x=>new RegExp(x.pattern).test(r.t)),matches=DESIGN_RULES.actions.filter(x=>x.id!=='explore'&&new RegExp(x.pattern).test(r.t));
 const x=pilot?{...pilot,kind:'reviewed',rule:'승인된 시범 사례',action:action.id}:{code:r.c,title:(r.a||subj)+' · '+action.label,concepts:action.concepts,facts:profile.focus+' 교과서에서 이 성취기준에 해당하는 구체적 자료·장면을 고릅니다.',relation:action.relation,think:action.think,focus:profile.focus+' 학생이 궁금해할 사진·실물·짧은 진술·표현물 중에서 고르고 출처를 남깁니다.',evidence:profile.evidence+'; '+action.evidence,feedback:action.feedback,transfer:'교과서에서 다룬 범위 안에서 대상이나 조건이 다른 사례를 골라, 같은 방법을 사용할 부분과 바꿀 부분을 살펴봅니다.',boundary:profile.boundary,kind:'shared',rule:subj+' 관점 + '+action.label+' 규칙',action:action.id};
 if(!pilot&&r.hae)x.boundary+=' 이 기준의 해설을 아래 원문에서 함께 확인하세요.';
 x.kind=pilot?'reviewed':'shared';x.matches=matches.map(y=>y.label);designCache.set(key,x);return x;
}
// Replace legacy generated concept fragments in indexes and every export consumer.
conceptsOf=function(r,k=6){return designFor(r).concepts.slice(0,k);};
function sourceRecord(r){return SOURCE_INDEX.records[r.c];}
function sourceLabel(r){const s=sourceRecord(r);return s.file+' · '+(s.pages.length?'PDF '+s.pages.join(', ')+'쪽':'본문 일치 위치 확인 필요')+(s.curriculumFromLevels?' (성취수준 공식 자료에 수록된 성취기준)':'');}
reviewSourceText=function(r){return sourceLabel(r)+'\n대조: '+sourceRecord(r).basis;};
reviewLink=function(host,label,file,page){const a=el('a',null,label);a.href='sources/'+encodeURIComponent(file)+(page?'#page='+page:'');a.target='_blank';a.rel='noopener';host.appendChild(a);};
addReviewSource=function(host,r){const s=sourceRecord(r),box=el('details','method-sources');box.appendChild(el('summary',null,'공식 문서·대조 범위'));const p=el('p');reviewLink(p,sourceLabel(r),s.file,s.pages[0]||s.candidatePages?.[0]);box.appendChild(p);if(s.variantNote){box.appendChild(el('p','src',s.variantNote));const alt=el('p');reviewLink(alt,'별책 원문 표기 비교',s.curriculumFile,s.curriculumCandidatePages?.[0]);box.appendChild(alt);}if(s.repairNote)box.appendChild(el('p','src',s.repairNote));const l=el('p');reviewLink(l,'성취수준: '+s.levelFile+' · '+(s.levelPages.length?'PDF '+s.levelPages.join(', ')+'쪽':'본문 일치 위치 확인 필요'),s.levelFile,s.levelPages[0]||s.levelCandidatePages?.[0]);box.appendChild(l);box.appendChild(el('p','src',s.basis+'입니다. 원본 데이터의 줄표·가운뎃점·공백 표기는 보존했습니다. '+(s.haeVerified===false?'해설의 전체 문자열은 자동 대조로 확인하지 못했습니다. PDF에서 확인하세요.':'')));host.appendChild(box);};
function releaseCard(r){const x=designFor(r),box=el('section','pilot-card');box.appendChild(el('div','review-kicker',x.kind==='reviewed'?'기준별 설계 도움 · 승인 사례':'교과·수행 규칙으로 구성한 설계 도움'));box.appendChild(el('h3',null,x.title));box.appendChild(el('p','src',x.kind==='reviewed'?DRAFT_NOTICE:'AI가 작성한 공통 규칙으로 구성한 초안입니다. 개별 수업 검증을 거친 답이 아니므로 교과서와 해설에 맞게 선택·수정하세요.'));
 const rail=el('div','inquiry-rail'),detail=el('div','inquiry-explanation');detail.setAttribute('aria-live','polite');const items=[['사실·사례',x.facts],['살펴볼 관점',x.concepts.join(' · ')+(x.kind==='shared'?' — 활동을 살펴보는 관점입니다. 교과의 핵심 개념으로 확정하지 말고 원문에서 고르세요.':'')],[x.kind==='reviewed'?'관계 가설':'관계 탐구 방향',x.relation],['전이',x.transfer]];items.forEach(([l,t],i)=>{const b=el('button','inquiry-stage'+(!i?' active':''));b.setAttribute('aria-pressed',String(!i));b.appendChild(el('strong',null,l));b.onclick=()=>{rail.querySelectorAll('button').forEach(z=>{z.classList.toggle('active',z===b);z.setAttribute('aria-pressed',String(z===b));});detail.textContent=t;};rail.appendChild(b);});detail.textContent=x.facts;box.append(rail,detail);const thought=el('div','qft-think');thought.appendChild(el('p',null,x.think));box.appendChild(thought);
 for(const [l,t] of [['QFT 질문 초점의 자료 후보',x.focus],['학습 증거와 피드백',x.evidence+'\n\n'+feedbackText(r)],['선택 근거와 적용 범위',x.rule+'\n성취기준에서 확인한 수행: '+(x.matches.join(', ')||'경험·성찰')+'\n'+x.boundary]]){const d=el('details','method-sources');d.appendChild(el('summary',null,l));d.appendChild(el('p','review-linked',t));box.appendChild(d);}if(r.hae){const d=el('details','method-sources');d.appendChild(el('summary',null,'성취기준 해설 · 원문 확인'));d.appendChild(el('p',null,r.hae));box.appendChild(d);}return box;
}
feedbackRows=function(r){const x=designFor(r);return [['근거나 수행 과정이 드러나지 않을 때',x.feedback,'실제 자료·수행에서 다시 볼 한 부분을 학생과 고르고 시도하게 합니다.',x.evidence],['도움을 받고 다시 시도할 때','학생이 이미 해낸 부분과 막힌 부분을 구분해, 필요한 도움 하나만 제안합니다.','같은 도움을 줄인 뒤 학생이 선택한 방법으로 다시 시도하게 합니다.','처음과 다음 수행의 차이, 학생이 설명한 수정 이유를 살핍니다.'],['새로운 사례로 확장할 때',x.transfer,'같은 방법을 쓸 수 있는 조건과 조정할 조건을 표시하게 합니다.','적용 결과와 바꾼 이유를 함께 확인합니다.']];};
const releaseWays={compare:['서·논술형','비교 기준과 근거를 표현한 기록'],solve:['서·논술형','풀이·표현·확인 과정'],create:['포트폴리오','시도·수정·최종 표현 모음'],inquire:['프로젝트','자료·과정·출처 기록'],practice:['관찰','실제 참여·실천 기록'],interpret:['구술·발표','자료와 설명을 연결한 기록'],explore:['관찰','경험·선택·성찰 기록']};
evalDraft=function(r){const x=designFor(r),w=releaseWays[x.action];return {ways:[{m:w[0],tool:w[1],source:w[0]==='관찰'?'app':'guide',why:'이 성취기준의 실제 수행과 학습 증거에 맞는지 교사가 선택합니다.'},{m:'관찰',tool:'수행 과정 기록',source:'app',why:'글로 드러내기 어려운 참여·수행을 확인할 때 선택합니다.'}].filter((v,i,a)=>a.findIndex(z=>z.m===v.m)===i),elements:[r.t],elementRows:[{t:r.t,cat:'성취기준 원문'}],mainCat:'성취기준의 수행',samples:(window.__EVAL||{})[r.c]||[],rubric:['A','B','C'].map(k=>[k,r[k]]),feedback:feedbackText(r),when:'학교 평가계획과 교과서 학습에 맞게 설정',count:'학교 평가계획에 따라 설정',area:domName(r)||r.a,thin:false};};
teachDraft=function(r){return {summary:r.t,steps:[],acts:[],topic:r.a};};
function releaseModes(p,r,t){const modes=el('div','qft-mode');[['student','학생 질문에서 시작'],['teacher','교사 설계·예시'],['success','SUCCESS 모델로 설계']].forEach(([k,l])=>{const b=el('button','btn'+(inquiryMode===k?' on':''),l);b.setAttribute('aria-pressed',String(inquiryMode===k));b.onclick=()=>{inquiryMode=k;renderDetail();};modes.appendChild(b);});p.appendChild(modes);}
qftPane=function(p,r){beforePilotQft(p,r);p.querySelector('.qft-package').after(releaseCard(r));};
panePlan=function(p,r,t){releaseModes(p,r,t);if(inquiryMode==='student')return qftPane(p,r);if(inquiryMode==='success')return successPane(p,r);if(isReviewSample(r)){const content=el('div');teacherPlan(content,r,t);content.querySelectorAll('.review-step').forEach((section,i)=>{const d=el('details','teacher-section');d.open=!i;const h=section.querySelector('h3');d.appendChild(el('summary',null,h?.textContent||'설계'));h?.remove();section.replaceWith(d);d.appendChild(section);});p.appendChild(content);}else p.appendChild(releaseCard(r));const b=el('button','btn on','설계 MD 내려받기');b.onclick=()=>download(r.c+'.md',qftDesignMd(r),'text/markdown;charset=utf-8');p.appendChild(b);};
paneMap=function(p,r){const x=designFor(r);p.appendChild(el('h3',null,x.kind==='reviewed'?'개념의 관계와 학습 증거':'관찰에서 설명·수정으로 이어 보기'));p.appendChild(el('p','src','설계 도움용 시각화입니다. 공식 위계나 인과 모형이 아닙니다.'));const flow=el('div','pilot-map');x.concepts.forEach((c,i)=>{flow.appendChild(el('div','review-node',c));if(i<2)flow.appendChild(el('span','pilot-map-edge','↔'));});p.appendChild(flow);p.appendChild(el('p','review-evidence',x.relation));for(const [l,t] of [['어떤 자료를 볼까?',x.facts],['무엇으로 확인할까?',x.evidence],['어디까지 적용할까?',x.boundary]]){const d=el('details','method-sources');d.appendChild(el('summary',null,l));d.appendChild(el('p',null,t));p.appendChild(d);}const b=el('button','btn','이 관계를 탐구 설계에서 살펴보기');b.onclick=()=>{S.tab='plan';renderDetail();};p.appendChild(b);};
domPicker=function(p,r){const d=el('details','method-sources'),ev=domainEvidence.get(r.c);d.appendChild(el('summary',null,'내용 체계 연결: '+(domName(r)||'보류')+' · '+(DOMPICK[r.c]?'교사 선택':ev.kind==='name'?'영역 이름 일치':'검토할 제안')));d.appendChild(el('p','src','단원→영역 연결은 공식 대응표가 아닙니다. 아래 후보의 공통 단어와 내용 체계를 비교하고 선택하세요. 교사의 기존 선택은 유지합니다.'));const s=el('select');s.setAttribute('aria-label','내용 체계 연결 영역');['',...(DOM[r.subj]||[]).map(x=>x.name)].forEach(name=>{const o=el('option',null,name||'연결 보류');o.value=name;s.appendChild(o);});s.value=domName(r)||'';s.onchange=()=>{DOMPICK[r.c]=s.value;try{localStorage.setItem('dompick2022',JSON.stringify(DOMPICK));}catch(e){reviewToast('저장하지 못했습니다.');}designCache.clear();for(const k of ['_cbi','_con','_end','_lens','_eval','_teach','_tc','_prof','_sub','_topic','_gr'])delete r[k];CONIDX.clear();buildConceptIndex();S.areas.clear();renderFilters();render();};d.appendChild(s);ev.candidates.forEach(c=>d.appendChild(el('p','src',c.name+' · 겹치는 단어: '+(c.hits.join(', ')||'없음'))));p.appendChild(d);};
// Explicit empty teacher selection means deferred, not fallback to an automatic guess.
const legacyDomName=domName;
// domName is declared const in baseline; build script replaces it with a mutable binding.
domName=function(r){return Object.prototype.hasOwnProperty.call(DOMPICK,r.c)?(DOMPICK[r.c]||null):r.dom||null;};
paneCs=function(p,r){domPicker(p,r);const d=domOf(r);if(!d){p.appendChild(el('p','src','연결할 영역을 선택하면 해당 영역의 내용 체계를 볼 수 있습니다.'));return;}p.appendChild(el('p','src','선택한 영역의 전체 자료입니다. 특정 문장을 이 성취기준의 공식 대응으로 확정하지 않습니다.'));p.appendChild(secTitle('핵심 아이디어 · '+d.name,'교육과정 수록 문장'));d.idea.forEach(t=>p.appendChild(el('p','review-evidence',t)));const ct=contentAllOf(r)||{};CATS.forEach(c=>{const details=el('details','method-sources');details.appendChild(el('summary',null,c+' · '+r.band));(ct[c]||[]).forEach(t=>details.appendChild(el('p',null,t)));p.appendChild(details);});};
paneStd=function(p,r){if(r.hae){p.appendChild(secTitle('성취기준 해설','원문 데이터'));p.appendChild(el('blockquote','quote',r.hae));}p.appendChild(secTitle('성취수준','원문 데이터'));['A','B','C'].forEach(k=>{const d=el('div','review-evidence');d.appendChild(el('strong',null,k));d.appendChild(el('p',null,r[k]||'수록 자료 없음'));p.appendChild(d);});addReviewSource(p,r);if((r.q||[]).length){const d=el('details','method-sources');d.appendChild(el('summary',null,'교육과정 탐구 활동 · 수록 자료'));r.q.forEach(t=>d.appendChild(el('p',null,t)));p.appendChild(d);}};
paneLesson=function(p,r){const x=designFor(r);quietNotice(p);domPicker(p,r);p.appendChild(secTitle('교과서에서 다룰 내용 정하기','교사의 선택'));p.appendChild(el('p',null,r.t));p.appendChild(el('p','src',DESIGN_RULES.subjects[r.subj].focus+' 교과서의 실제 자료와 활동을 정하고 아래 증거가 드러나는지 확인하세요.'));p.appendChild(secTitle('살펴볼 학습 증거','설계 제안'));p.appendChild(el('p','review-evidence',x.evidence));p.appendChild(secTitle('평가 방법 후보','교사가 선택'));const grid=el('div','method-grid');evalDraft(r).ways.forEach(w=>{const c=el('div','method-card');c.appendChild(el('strong',null,w.m));c.appendChild(el('p',null,w.why));c.appendChild(el('p','src','도구: '+w.tool+' · '+(w.source==='guide'?'교육부 안내 명칭':'앱 제안')));grid.appendChild(c);});p.appendChild(grid);methodSources(p);p.appendChild(secTitle('피드백 방안','설계 제안'));feedbackRows(r).forEach((row,i)=>{const d=el('details','feedback-case');d.open=!i;d.appendChild(el('summary',null,row[0]));row.slice(1).forEach(t=>d.appendChild(el('p',null,t)));p.appendChild(d);});const edit=el('details','feedback-case');edit.appendChild(el('summary',null,'피드백 수정·저장'));const ta=el('textarea');ta.value=feedbackText(r);ta.rows=10;ta.setAttribute('aria-label','피드백 방안 편집');const save=el('button','btn','피드백 저장');save.onclick=()=>{try{localStorage.setItem('review-feedback-v2',JSON.stringify({...feedbackEdits,[r.c]:ta.value}));feedbackEdits[r.c]=ta.value;reviewToast('저장했습니다. 내보내기에도 반영됩니다.');}catch(e){reviewToast('저장하지 못했습니다. 복사해 보관해 주세요.');}};edit.append(ta,save);p.appendChild(edit);const cp=el('button','btn','피드백 복사');cp.onclick=()=>copy(feedbackText(r),cp);p.appendChild(cp);p.appendChild(secTitle('성취수준과 대조하기','원문 데이터'));['A','B','C'].forEach(k=>p.appendChild(el('p','review-evidence',k+' · '+r[k])));};
function designMdPart(r){const x=designFor(r);return '## 기준별 설계 도움 · '+x.rule+'\n\n'+[['facts','사실·사례'],['relation',x.kind==='reviewed'?'관계 가설':'관계 탐구 방향'],['think','교사의 설계 질문'],['focus','QFT 자료 후보'],['evidence','학습 증거'],['transfer','전이'],['boundary','적용 범위']].map(([k,l])=>'### '+l+'\n'+x[k]).join('\n\n')+'\n\n살펴볼 관점: '+x.concepts.join(' · ')+'\n교사가 선택·수정할 내용과 이유: ______\n';}
qftDesignMd=function(r){const s=sourceRecord(r);let md=beforePilotMd(r);if(s.variantNote)md+='\n공식 자료 간 표기 차이: '+s.variantNote+' '+s.curriculumFile+' PDF '+s.curriculumCandidatePages.join(', ')+'쪽\n';if(s.repairNote)md+='\n수식 표기 복원: '+s.repairNote+'\n';md=md.replace(/출처: 앱의 성취수준 자료[^\n]*/,'출처: '+s.levelFile+' · '+(s.levelPages.length?'PDF '+s.levelPages.join(', ')+'쪽':'위치 확인 필요'));md=md.replace('## 2. 교사가 먼저 생각해 볼 것',designMdPart(r)+'\n## 2. 교사가 먼저 생각해 볼 것');md+='\n## 평가 방법 후보 · 교사가 선택\n'+evalDraft(r).ways.map(w=>'- '+w.m+' / '+w.tool+' / '+(w.source==='guide'?'교육부 안내 명칭':'앱 제안')).join('\n')+'\n\n## 피드백 방안 · 교사 편집 포함\n'+feedbackText(r)+'\n\n## 내보낸 버전\nv'+APP_VERSION+'\n';if(isReviewSample(r))md+='\n## 기존에 편집한 사회 대표 사례 설계\n'+reviewExportText();return md;};
mdOf=rows=>rows.map(qftDesignMd).join('\n\n---\n\n');
docOf=rows=>'<html><head><meta charset="utf-8"><title>수업 설계 v'+APP_VERSION+'</title></head><body>'+rows.map(r=>'<pre style="white-space:pre-wrap;font-family:Malgun Gothic,sans-serif;line-height:1.7">'+esc2(qftDesignMd(r))+'</pre>').join('<hr>')+'</body></html>';
planCSV=function(rows){const out=[['성취기준 코드','성취기준 원문','내용 체계 연결(검토)','학습 증거 제안','평가 방법 후보','피드백(교사 편집 포함)','성취수준 구분','성취수준 원문','출처']];rows.forEach(r=>['A','B','C'].forEach(k=>out.push([r.c,r.t,domName(r)||'보류',designFor(r).evidence,evalDraft(r).ways.map(w=>w.m).join(' / '),feedbackText(r),k,r[k],reviewSourceText(r)])));return '\uFEFF'+out.map(row=>row.map(csvEsc).join(',')).join('\r\n');};
toCSV=rows=>'\uFEFF'+[['성취기준 코드','성취기준 원문','성취수준 A','성취수준 B','성취수준 C','출처'],...rows.map(r=>[r.c,r.t,r.A,r.B,r.C,reviewSourceText(r)])].map(row=>row.map(csvEsc).join(',')).join('\r\n');
startReview=function(){$('#q').setAttribute('aria-label','성취기준 검색');$('#cartPlain').onclick=()=>copy(cartRows().map(r=>r.c+' '+r.t).join('\n'),$('#cartPlain'));$('#btnAll').onclick=()=>{const rows=listedRows(),all=cartHasAll(rows);rows.forEach(r=>all?S.cart.delete(r.c):S.cart.add(r.c));saveCart();render();};syncCartAll();};
// 전체 담기 becomes 전체 해제 once every listed standard is in the basket. filtered() resets search highlight state, so restore it.
function listedRows(){const h=HILITE,x=RELAX,rows=filtered();HILITE=h;RELAX=x;return rows;}
function cartHasAll(rows){return rows.length>0&&rows.every(r=>S.cart.has(r.c));}
function syncCartAll(){const b=$('#btnAll');if(!b||!STD)return;const all=cartHasAll(listedRows());b.textContent=all?'전체 해제':'전체 담기';b.setAttribute('aria-pressed',String(all));}
const renderBeforeCartAll=render;render=function(){renderBeforeCartAll();syncCartAll();};
const updateCartBeforeCartAll=updateCart;updateCart=function(){updateCartBeforeCartAll();syncCartAll();};
