/* Student-authored questions are separate from AI/teacher examples. */
const QFT_SOURCE='Source: The Right Question Institute (RQI). The Question Formulation Technique (QFT) was created by RQI. Visit rightquestion.org for more information and free resources.';
let inquiryMode='student',qftStage=0;
const qftSessions=new Map();
function qftData(r){if(qftSessions.has(r.c))return qftSessions.get(r.c);let d={version:1,code:r.c,focus:isReviewSample(r)?'같은 장소, 서로 다른 느낌':'',criterion:'이번 탐구에서 더 알아보고 싶은 질문',rulesReflection:'',typesReflection:'',next:'',reflection:'',rows:[]};try{const x=JSON.parse(localStorage.getItem('qft-v1-'+r.c)||'null');if(qftValid(x,r.c))d=x;}catch(e){}qftSessions.set(r.c,d);return d;}
function qftValid(x,code){return x&&x.version===1&&x.code===code&&['focus','criterion','rulesReflection','typesReflection','next','reflection'].every(k=>typeof x[k]==='string')&&Array.isArray(x.rows)&&x.rows.length<=200&&x.rows.every(q=>['original','type','changed','changedType','reason'].every(k=>typeof q[k]==='string')&&typeof q.priority==='boolean');}
function saveQft(r){try{localStorage.setItem('qft-v1-'+r.c,JSON.stringify(qftData(r)));const s=$('#qftStatus');if(s)s.textContent='이 브라우저에 자동 저장됨';}catch(e){const s=$('#qftStatus');if(s)s.textContent='자동 저장 실패 · 작업 파일로 보관하세요';}}
function qftField(host,obj,key,label,r,placeholder=''){const l=el('label','review-field',label),t=el('textarea');t.value=obj[key];t.placeholder=placeholder;t.rows=3;t.oninput=()=>{obj[key]=t.value;saveQft(r);};l.appendChild(t);host.appendChild(l);return t;}
function qftText(r){const d=qftData(r);return '# 학생 질문으로 시작하는 탐구\n'+r.c+' '+r.t+'\n\n질문 초점: '+d.focus+'\n선택 기준: '+d.criterion+'\n\n'+d.rows.map((q,i)=>`${i+1}. ${q.original}\n유형: ${q.type||'미분류'}\n바꾼 질문: ${q.changed}\n바꾼 유형: ${q.changedType}\n선택: ${q.priority?'선택함':'보류'} / 이유: ${q.reason}`).join('\n\n')+'\n\n규칙 돌아보기: '+d.rulesReflection+'\n질문 유형의 장단점: '+d.typesReflection+'\n다음 탐구: '+d.next+'\n성찰: '+d.reflection+'\n\n'+QFT_SOURCE+'\nhttps://rightquestion.org/what-is-the-qft/';}
function qftPane(p,r){const d=qftData(r);p.appendChild(el('div','review-kicker','학생이 만들고 · 학생이 고르고 · 학생이 돌아보기'));p.appendChild(el('h2','review-heading','질문하는 주체를 학생으로'));
 p.appendChild(el('p','review-muted','교사는 질문을 불러올 자료와 활동 조건을 준비합니다. 학생이 만든 질문은 답을 정해 두지 않고 기록하고, 탐구할 질문과 선택 이유도 학생이 정합니다.'));
 const titles=['질문 초점','질문 만들기','질문 다듬기','질문 고르기','탐구에 쓰기','돌아보기'],nav=el('nav','qft-steps');nav.setAttribute('aria-label','학생 질문 활동 단계');titles.forEach((t,i)=>{const b=el('button','qft-step'+(i===qftStage?' on':''),(i+1)+'. '+t);b.setAttribute('aria-current',i===qftStage?'step':'false');b.onclick=()=>{qftStage=i;renderDetail();};nav.appendChild(b);});p.appendChild(nav);
 const body=el('section','qft-body');body.appendChild(el('h3',null,(qftStage+1)+'. '+titles[qftStage]));p.appendChild(body);
 if(qftStage===0){body.appendChild(el('p',null,'학생에게 답을 요구하는 질문 대신 사진·자료·짧은 진술을 질문 초점(QFocus)으로 준비하세요. 학생 질문을 미리 제시하지 않습니다.'));qftField(body,d,'focus','질문을 불러올 자료 또는 짧은 진술',r,'교과서에서 고른 자료의 설명이나 제시할 짧은 진술');body.appendChild(el('p','src',isReviewSample(r)?'‘같은 장소, 서로 다른 느낌’은 교사가 검토할 AI 작성 예시입니다. 실제 학생 질문은 다음 단계에서 직접 기록합니다.':'자료는 교과서와 성취기준에 맞게 교사가 선택합니다.'));qftField(body,d,'criterion','질문을 고를 때 사용할 기준',r);}
 if(qftStage===1){const rules=el('div','qft-rules');['떠오르는 질문을 충분히 모으기','만드는 동안 평가·토의·답변은 잠시 미루기','말한 표현을 그대로 기록하기','진술이 나오면 질문으로 표현하기'].forEach((t,i)=>rules.appendChild(el('p',null,(i+1)+'. '+t)));body.appendChild(rules);qftField(body,d,'rulesReflection','지키기 어려울 것 같은 규칙과 방법',r);body.appendChild(el('blockquote','review-evidence',d.focus||'먼저 질문 초점에서 제시할 자료를 정하세요.'));const input=el('textarea');input.id='qftNew';input.setAttribute('aria-label','학생이 만든 질문');input.placeholder='학생이 말한 질문을 그대로 적습니다.';input.rows=3;body.appendChild(input);const add=el('button','btn on','질문 기록');add.onclick=()=>{if(!input.value.trim())return;if(d.rows.length>=200){reviewToast('작업 파일로 보관하고 새 활동에서 이어 주세요.');return;}d.rows.push({original:input.value,type:'',changed:'',changedType:'',priority:false,reason:''});saveQft(r);renderDetail();};body.appendChild(add);d.rows.forEach((q,i)=>body.appendChild(el('p','qft-original',(i+1)+'. '+q.original)));}
 if(qftStage===2){body.appendChild(el('p',null,'짧게 답할 수 있는 닫힌 질문과 설명이 필요한 열린 질문으로 구분해 보세요. 각 유형의 장단점을 생각하고, 양쪽 방향으로 바꿔 봅니다. 열린 질문이 언제나 더 좋은 것은 아닙니다.'));qftField(body,d,'typesReflection','두 유형의 장점과 아쉬운 점',r);d.rows.forEach((q,i)=>{const card=el('div','qft-card');card.appendChild(el('p','qft-original',(i+1)+'. '+q.original));for(const [key,label] of [['type','처음 질문 유형'],['changedType','바꾼 질문 유형']]){const l=el('label',null,label+' '),s=el('select');s.setAttribute('aria-label',label+' '+(i+1));['','닫힌 질문','열린 질문'].forEach(v=>{const o=el('option',null,v||'학생이 분류하기');o.value=v;s.appendChild(o);});s.value=q[key];s.onchange=()=>{q[key]=s.value;saveQft(r);};l.appendChild(s);card.appendChild(l);}qftField(card,q,'changed','바꾼 질문 '+(i+1),r);body.appendChild(card);});}
 if(qftStage===3){body.appendChild(el('p','review-evidence','선택 기준: '+d.criterion));body.appendChild(el('p',null,'학생이 질문을 선택하고 이유를 설명합니다. 선택하지 않은 질문도 목록에 남겨 나중에 다시 볼 수 있습니다.'));d.rows.forEach((q,i)=>{const card=el('div','qft-card'),l=el('label'),cb=el('input');cb.type='checkbox';cb.checked=q.priority;cb.onchange=()=>{q.priority=cb.checked;saveQft(r);};l.append(cb,document.createTextNode(' '+(i+1)+'. '+(q.changed||q.original)));card.appendChild(l);if(q.changed)card.appendChild(el('p','src','처음 질문: '+q.original));qftField(card,q,'reason','선택하거나 보류한 이유 '+(i+1),r);body.appendChild(card);});}
 if(qftStage===4){const chosen=d.rows.filter(q=>q.priority);if(!chosen.length)body.appendChild(el('p','review-muted','선택한 질문이 없습니다. 질문 고르기에서 선택하거나 모든 질문을 다시 살펴보세요.'));chosen.forEach(q=>body.appendChild(el('p','qft-original',q.changed||q.original)));qftField(body,d,'next','학생이 정한 알아볼 방법과 남길 증거',r,'어떤 자료를 살펴보거나 누구에게 물어볼까? 알아낸 것을 어떻게 남길까?');if(isReviewSample(r)){const send=el('button','btn','선택 질문을 교사 설계에 추가');send.onclick=()=>{let n=0;chosen.forEach(q=>{const text=q.changed||q.original;if(inquiryQuestions.length<50&&!inquiryQuestions.some(x=>x.q===text)){inquiryQuestions.push({id:'student'+Date.now()+Math.random().toString(16).slice(2),q:text,e:d.next});n++;}});markInquiryChanged();try{localStorage.setItem(REVIEW_KEY,JSON.stringify(reviewDocument()));reviewSaved=true;reviewToast(n+'개를 교사 설계에 추가·저장했습니다. (중복 제외 · 최대 50개)');}catch(e){reviewToast('교사 설계에 추가했습니다. 설계 저장을 확인하세요.');}};body.appendChild(send);}}
 if(qftStage===5){qftField(body,d,'reflection','질문하며 알게 된 점과 다음에 달리 해 볼 점',r,'내 질문은 어떻게 달라졌나? 내가 고른 질문은 탐구에 어떤 영향을 주었나?');body.appendChild(el('p','src','질문의 수나 열린 질문의 비율을 학생 주도성 점수로 환산하지 않습니다. 학생이 선택한 이유와 활동에 반영된 과정을 살펴보세요.'));}
 if(qftStage>=2&&qftStage<=3&&!d.rows.length)body.appendChild(el('p','review-muted','아직 학생 질문이 없습니다. 질문 만들기에서 기록해 주세요.'));
 const bar=el('div','qft-actions');if(qftStage>0){const prev=el('button','btn','이전');prev.onclick=()=>{qftStage--;renderDetail();};bar.appendChild(prev);}if(qftStage<5){const next=el('button','btn on','다음');next.onclick=()=>{qftStage++;renderDetail();};bar.appendChild(next);}const status=el('span','src','학생 질문은 AI 예시와 별도로 보관됩니다.');status.id='qftStatus';bar.appendChild(status);p.appendChild(bar);
 const files=el('div','dact'),save=el('button','btn','학생 질문 파일 저장');save.onclick=()=>download('학생질문_'+r.c+'.json',JSON.stringify({...d,source:QFT_SOURCE},null,2),'application/json');files.appendChild(save);const cp=el('button','btn','학생 질문 기록 복사');cp.onclick=()=>copy(qftText(r),cp);files.appendChild(cp);const input=el('input');input.type='file';input.accept='.json';input.hidden=true;const load=el('button','btn','학생 질문 파일 불러오기');load.onclick=()=>input.click();input.onchange=async()=>{try{const f=input.files[0];if(!f||f.size>2000000)throw Error();const x=JSON.parse(await f.text());if(!qftValid(x,r.c))throw Error();if(!confirm('이 성취기준의 학생 질문 기록을 파일 내용으로 바꿀까요?'))return;qftSessions.set(r.c,x);saveQft(r);renderDetail();}catch(e){reviewToast('현재 성취기준의 학생 질문 파일인지 확인해 주세요.');}};files.append(load,input);p.appendChild(files);
 const source=el('details','method-sources');source.appendChild(el('summary',null,'QFT 안내와 출처'));source.appendChild(el('p',null,'『한 가지만 바꾸기』와 연결되는 핵심은 학생이 스스로 질문하는 역할을 맡는 것입니다. 이 화면은 QFT를 참고해 만든 한국어 활동 기록 도구이며 공식 번역본이 아닙니다.'));source.appendChild(el('p','src',QFT_SOURCE));const a=el('a',null,'RQI의 QFT 절차 보기');a.href='https://rightquestion.org/what-is-the-qft/';a.target='_blank';a.rel='noopener';source.appendChild(a);p.appendChild(source);
}
const teacherPlan=panePlan;
panePlan=function(p,r,t){const modes=el('div','qft-mode');[['student','학생 질문에서 시작'],['teacher','교사 설계·예시']].forEach(([k,l])=>{const b=el('button','btn'+(inquiryMode===k?' on':''),l);b.setAttribute('aria-pressed',String(inquiryMode===k));b.onclick=()=>{inquiryMode=k;renderDetail();};modes.appendChild(b);});p.appendChild(modes);if(inquiryMode==='student')return qftPane(p,r);const content=el('div');teacherPlan(content,r,t);content.querySelectorAll('.review-step').forEach((s,i)=>{const d=el('details','teacher-section');d.open=i===0;const h=s.querySelector('h3');d.appendChild(el('summary',null,h?.textContent||'설계'));if(h)h.remove();s.replaceWith(d);d.appendChild(s);});p.appendChild(content);};
