/* QFT planning companion: read here, develop the portable MD with the teacher. */
const QFT_CREDIT='Source: The Question Formulation Technique was created by Dan Rothstein and Luz Santana, co-founders of the Right Question Institute (rightquestion.org)';
const QFT_GUIDE=[
 {title:'질문 초점',role:'교사는 질문을 불러올 자료를 준비합니다. 학생에게 제시할 질문 자체를 정해 주는 단계는 아닙니다.',think:'이 성취기준에서 학생이 직접 궁금해하고 알아보길 바라는 것은 무엇인가요?',choose:'사진은 관찰을, 짧은 진술은 해석의 차이를, 교과서 자료는 학습 맥락과의 연결을 도울 수 있습니다. 어느 자료가 우리 반의 경험과 연결될지 비교해 보세요.',student:'사진·자료·짧은 진술을 접하고 자신이 궁금한 점을 찾습니다.',material:'PPT에는 실제로 고른 자료와 출처를 넣을 공간, 교사 메모에는 선정 이유를 남깁니다.',blank:'교과서·쪽 / 제시할 자료 / 선정 이유 / 설명을 덧붙이지 않아도 이해할 수 있는지'},
 {title:'질문 만들기',role:'질문 생성 규칙을 안내하고 학생이 규칙의 어려움을 생각하게 합니다. 질문을 만드는 동안 판단·답변을 미루고 표현 그대로 기록하도록 돕습니다.',think:'말이나 글로 질문하기 어려운 학생도 자기 질문을 남기려면 어떤 지원이 필요할까요?',choose:'개별 메모 후 함께 모으기, 짝이 말한 질문을 그대로 받아 적기, 학생이 녹음 후 확인하기 등을 비교하세요. 지원 방식이 질문의 내용까지 대신 정하지 않게 합니다.',student:'질문을 충분히 만들고, 진술은 질문으로 바꾸며 번호를 붙여 그대로 남깁니다.',material:'PPT에는 네 가지 규칙, 학습지에는 질문 번호와 넉넉한 빈 기록 공간을 둡니다.',blank:'기록 방식 / 참여 지원 / 생성 중 교사의 중립적인 반응'},
 {title:'질문 다듬기',role:'열린·닫힌 질문을 구분하고 각각의 장단점을 비교하도록 안내합니다. 두 방향으로 바꿔 볼 기회를 줍니다.',think:'학생이 질문 유형의 이름보다 답에서 얻을 정보의 차이를 발견하게 하려면 무엇을 비교하게 할까요?',choose:'닫힌 질문은 예·아니요 또는 한 단어로 답할 수 있고, 열린 질문에는 설명이 필요합니다. 원래 질문을 지우지 않고 바꾼 질문을 옆에 둡니다. 열린 질문만 좋은 질문으로 평가하지 않습니다.',student:'자기 질문을 분류하고, 닫힌 질문→열린 질문과 열린 질문→닫힌 질문으로 바꿔 보며 얻을 정보의 차이를 살핍니다.',material:'학습지에 처음 질문 / 유형 / 바꾼 질문 / 유형 / 달라진 점을 나란히 배치합니다.',blank:'유형별 장단점 비교 방법 / 처음 표현을 보존하는 방법'},
 {title:'질문 고르기',role:'학습 목적과 다음 활동에 맞는 선택 기준을 준비합니다. 그 기준 안에서 어떤 질문을 탐구할지 학생이 결정하고 이유를 설명하게 합니다.',think:'학생의 선택이 이후 수업을 실제로 바꾸는 부분은 어디인가요?',choose:'자료 읽기로 알아볼 질문, 서로 다른 경험을 비교할 질문, 조사로 확인할 질문 등 다음 활동과 맞는 기준을 검토하세요. 선택 개수는 활동 여건에 맞게 정하고 보류한 질문도 남깁니다.',student:'우선 탐구할 질문의 번호와 선택 이유를 설명하고, 처음 목록에서 언제 나온 질문인지 돌아봅니다.',material:'PPT에는 선택 기준 자리, 학습지에는 질문 번호 / 선택 이유 / 보류 질문을 둡니다.',blank:'선택 기준 / 선택 범위 / 학생에게 맡길 결정 / 보류 질문을 다시 볼 때'},
 {title:'탐구에 쓰기',role:'선택된 질문이 실제 자료 읽기·관찰·대화 등에 이어지도록 지원합니다. 질문이 모인 뒤 탐구 경로를 조정할 여지를 둡니다.',think:'어떤 질문이 나오느냐에 따라 자료나 활동을 어떻게 달리 제공할 수 있을까요?',choose:'교과서에서 찾아볼 수 있는 질문과 추가 관찰·대화가 필요한 질문을 구분해 볼 수 있습니다. 사전 설계에는 가능한 경로만 남기고 실제 질문이 나오면 구체화하세요.',student:'고른 질문을 알아볼 방법을 정하고, 자료와 자신의 생각을 구별해 근거를 남깁니다.',material:'학습지에 선택 질문 / 알아볼 방법 / 자료·쪽 / 알게 된 점 / 아직 남은 질문을 마련합니다.',blank:'가능한 탐구 경로 / 준비할 자료 / 실제 질문 후 바꿀 부분 / 살펴볼 학습 증거'},
 {title:'돌아보기',role:'질문 과정과 배운 내용 모두를 돌아보게 합니다. 기록을 보고 다음 탐구를 도울 피드백을 생각합니다.',think:'학생이 무엇을 선택했고 그 선택이 배움에 어떤 영향을 주었는지 어디에서 확인할 수 있을까요?',choose:'처음과 나중 질문을 비교하거나, 질문 덕분에 알게 된 점과 다음에 달리 해 볼 점을 살펴보세요. 질문 수나 열린 질문 비율로 학생 주도성을 점수화하지 않습니다.',student:'질문이 달라진 과정, 선택이 탐구에 준 영향, 배운 내용과 다음 질문을 표현합니다.',material:'PPT에는 성찰 안내, 학습지에는 자기 설명과 다음 질문을 적을 공간을 둡니다.',blank:'볼 기록 / 학생에게 되돌려 줄 질문 / 다음 수업에 반영할 점'}
];
function qftCoachPrompt(){return `당신은 교사의 생각을 구체화하는 수업 설계 동료입니다. 아래 QFT 설계 MD를 바탕으로 대화해 주세요.
1. 먼저 교사가 적은 생각을 짧게 정리하고, 아직 결정하지 않은 것 가운데 수업 방향을 바꾸는 질문을 최대 3개만 물어보세요. 답을 기다린 뒤 다음 단계로 진행하세요.
2. 선택이 어려운 부분에는 서로 다른 선택지 2~3개와 각각의 장점·조건을 제시하세요. 교사의 의도를 확인하지 않고 하나를 확정하지 마세요. 이미 제공된 정보를 다시 묻지 마세요.
3. 교사가 초안을 원하면 가정을 표시하고 수정할 부분을 남기세요. 교사가 고른 방향을 근거로 먼저 수업 설계 얼개를 만들고, 확인 후 요청한 자료(PPT 얼개 또는 학습지)를 구체화하세요.
4. 성취기준·성취수준·해설의 원문과 코드는 그대로 인용하고 출처를 유지하세요. 원문과 설계 제안을 명확히 구분하세요. 교과서 내용·쪽·사진은 제공받은 것만 사용하고, 없으면 [교사가 자료 선택]으로 남기세요. 차시별 흐름은 만들지 마세요.
5. QFT에서는 학생이 질문을 생성·변환·선택하고 이유를 설명합니다. 예상 학생 질문·모범 답을 학생 자료의 빈칸에 채우거나, 교사의 개념 관계 가설을 학생이 도달할 유일한 답으로 제시하지 마세요. 개념·관계는 학생 질문과 근거를 본 뒤 다시 검토하세요.
6. PPT는 슬라이드별 목적 / 화면 문구 / 교사 진행 메모 / 넣을 자료·출처 / 미정 사항으로 작성하세요. 학습지는 학생용 빈 기록 공간과 교사용 진행·피드백 메모를 분리하세요. 난도·읽기와 쓰기 부담·인쇄 분량을 교사와 정하세요.
7. 실제 학생 질문이 생긴 뒤 제공받으면, 학생의 원래 표현을 보존하면서 탐구 경로 수정안을 제안하세요. 선택을 대신하거나 가상의 학생 응답을 실제 기록처럼 쓰지 마세요.
8. 생성 자료는 검토용 초안이라고 표시하고, QFT 출처 문구도 자료에 포함하세요.`;}
function qftDesignMd(r){
 const out=['# 학생 질문에서 시작하는 QFT · 교사 설계 노트','','이 문서는 AI가 구성한 설계 도움 초안입니다. 교육과정 원문과 우리 반 맥락에 맞게 확인하고 수정·보완하세요. 빈칸은 교사의 결정을 위한 자리이며 모두 채울 필요는 없습니다.','','## 1. 교육과정 근거 · 원문','','### 성취기준',r.c+' '+r.t,'','출처: '+reviewSourceText(r)];
 if(r.hae)out.push('','### 성취기준 해설 · 원문',r.hae);
 if(['A','B','C'].some(k=>r[k]))out.push('','### 성취수준 · 앱에 수록된 원문',...['A','B','C'].filter(k=>r[k]).map(k=>k+': '+r[k]),'',isReviewSample(r)?'출처: '+REVIEW_LEVEL_PDF+' · 인쇄 34쪽 / PDF 38쪽':'출처: 앱의 성취수준 자료. 항목별 공식 문서·쪽은 교사가 확인해 기록: ______');
 out.push('','---','','## 2. 교사가 먼저 생각해 볼 것 · 설계 메모','','- 우리 반이 이미 경험하거나 알고 있는 것: ______','- 교과서·단원·실제로 사용할 쪽과 자료: ______','- 학생이 직접 알아보길 바라는 내용과 그 이유: ______','- 학생이 결정할 부분 / 교사가 준비할 조건: ______','- 참여·읽기·쓰기에서 필요한 지원: ______','- 개념과 관계에 대한 현재의 생각(잠정 가설, 학생에게 정답으로 제시하지 않기): ______','- 아직 고민인 것, 설계 동료와 먼저 이야기할 것: ______');
 out.push('','## 3. QFT 단계별 설계 질문','','질문 생성 규칙: 충분히 질문하기 / 생성 중 토의·평가·답변 미루기 / 말한 그대로 기록하기 / 진술은 질문으로 바꾸기. 규칙을 소개한 뒤 학생이 지키기 어려울 규칙을 스스로 생각하게 합니다.');
 QFT_GUIDE.forEach((s,i)=>out.push('',`### ${i+1}. ${s.title}`,'','교사의 역할: '+s.role,'','생각해 볼 질문: '+s.think,'','선택을 돕는 관점: '+s.choose,'','학생이 하는 일: '+s.student,'','자료로 옮길 때: '+s.material,'','내 결정 또는 남겨 둘 고민 ('+s.blank+'): ______'));
 out.push('','## 4. PPT 얼개 · 교사가 선택한 방향으로 구체화','','아래는 슬라이드 역할의 후보입니다. 장수·표현·자료는 교사가 정하고, 학생 질문이 생긴 뒤 조정합니다. 차시 배분표가 아닙니다.','','| 역할 후보 | 화면에 담을 것 | 교사 진행 메모·결정 |','| --- | --- | --- |','| 질문 초점 제시 | [교사가 선택한 사진·자료·진술과 출처] | 설명을 어디까지 줄일까? ______ |','| 생성 규칙 안내 | 네 가지 규칙과 규칙 돌아보기 | 참여 지원 방식: ______ |','| 질문 모으기 | 빈 질문 기록 안내 | 말한 표현을 보존하는 방법: ______ |','| 질문 바꾸기 | 열린·닫힌 유형 안내, 양방향 변환 자리 | 두 유형의 장단점을 어떻게 비교할까? ______ |','| 질문 선택하기 | [교사가 정한 선택 기준], 선택 이유 안내 | 학생에게 맡길 결정: ______ |','| 탐구 연결하기 | 선택 질문 → 방법 → 근거의 빈 연결 구조 | 실제 질문 후 넣을 자료: ______ |','| 성찰하기 | 질문의 변화·배운 점·다음 질문 | 살펴볼 기록과 피드백: ______ |',
 '','## 5. 학습지 구성 · 학생이 채울 공간','','인쇄 크기·분량: ______ / 개별·모둠 사용: ______ / 글 대신 표현할 방법: ______','','### 학생용 기록 틀','','질문 초점 자료: [교사가 선택한 자료 또는 자료를 볼 위치]','','**질문 모으기** — 질문 번호 / 학생이 말한 그대로 (필요한 만큼 빈 줄을 추가)','','1. ________________________________________','2. ________________________________________','3. ________________________________________','','**질문 다듬기**','','| 처음 질문 번호·표현 | 처음 유형 | 바꾼 질문 | 바꾼 유형 | 얻을 정보의 차이 |','| --- | --- | --- | --- | --- |','| ______ | ______ | ______ | ______ | ______ |','| ______ | ______ | ______ | ______ | ______ |','','닫힌→열린, 열린→닫힌 두 방향을 시도해 봅니다. 각 유형의 장점·아쉬운 점: ______','','**질문 선택하기** — 선택 기준: [교사가 결정]','','선택 질문 번호: ______ / 고른 이유: ______ / 처음 목록에서 나온 순서: ______','보류한 질문과 다시 살펴볼 때: ______','','**탐구에 쓰기**','','선택한 질문: ______ / 알아볼 방법: ______','자료·쪽 또는 관찰 기록: ______ / 그 자료에서 확인한 내용: ______','내 생각과 이를 뒷받침하는 근거: ______ / 아직 남은 질문: ______','','**돌아보기**','','처음과 나중의 질문에서 달라진 점: ______','내 선택이 탐구에 준 영향: ______ / 새로 배운 내용: ______','다음에 달리 해 볼 점과 새 질문: ______',
 '','### 교사용 진행·피드백 메모 (학생용과 분리)','','- 생성 중에는 질문의 우열을 판단하지 않고 표현 그대로 기록하도록 돕습니다.','- 탐구 후 볼 증거: [질문 변화·선택 이유·근거 기록 중 교사가 고르기] ______','- 관찰한 구체적인 모습 → 되돌려 줄 질문 → 다시 시도할 기회: ______','- 예: 선택 이유가 모호한 경우, 선택 기준과 질문의 어떤 부분이 이어지는지 설명할 기회를 줄 수 있습니다. 우리 반에 사용할 표현은 교사가 정합니다.','- 공식 성취수준과 대조하여 확인할 내용: ______','- 학생 질문을 보고 수정할 자료·활동: ______',
 '','## 6. AI와 함께 설계·자료 만들기','','아래 요청문과 이 문서를 함께 전달하세요. 먼저 고민을 나누고, 선택한 방향에 따라 자료를 만듭니다.','',qftCoachPrompt(),
 '','## 7. 출처와 사용 안내','',QFT_CREDIT,'https://rightquestion.org/what-is-the-qft/','','QFT를 참고한 한국어 설계 도움자료이며 공식 번역본이 아닙니다. QFT 자료를 활용한 결과물에도 출처를 표시하세요. RQI는 출처를 포함한 비상업적 사용·수정·공유를 안내합니다. 교육과정 원문과 위 설계 제안을 구분해 사용하세요.');
 return out.join('\n')+'\n';
}
qftPane=function(p,r){
 p.appendChild(el('div','review-kicker','단계 살펴보기 → 내 생각 정리 → 수업 자료로 발전시키기'));
 p.appendChild(el('h2','review-heading','학생 질문을 위한 수업, 교사의 생각부터'));
 p.appendChild(el('p','review-muted','여기서는 단계와 설계 관점을 살펴보세요. MD를 내려받아 교사의 고민을 정리하고, AI와 대화하며 PPT 얼개와 학습지로 발전시킬 수 있습니다.'));
 const pack=el('section','qft-package');pack.appendChild(el('strong',null,'QFT 설계 노트 · PPT 얼개 · 학습지 틀 · AI 대화 요청문'));
 pack.appendChild(el('p','src','선택한 성취기준의 원문과 출처가 함께 담깁니다. AI가 구성한 도움 초안이므로 수업에 맞게 확인·수정해 주세요.'));
 const actions=el('div','qft-actions'),save=el('button','btn on','QFT 설계 MD 내려받기'),cp=el('button','btn','QFT 설계 MD 복사');save.onclick=()=>download('QFT_설계노트_'+r.c.replace(/[\[\]]/g,'')+'.md',qftDesignMd(r),'text/markdown;charset=utf-8');cp.onclick=()=>copy(qftDesignMd(r),cp);actions.append(save,cp);pack.appendChild(actions);p.appendChild(pack);
 const nav=el('nav','qft-steps');nav.setAttribute('aria-label','QFT 설계 단계');QFT_GUIDE.forEach((s,i)=>{const b=el('button','qft-step'+(i===qftStage?' on':''),(i+1)+'. '+s.title);b.setAttribute('aria-current',i===qftStage?'step':'false');b.onclick=()=>{qftStage=i;renderDetail();};nav.appendChild(b);});p.appendChild(nav);
 const s=QFT_GUIDE[qftStage],body=el('section','qft-body');body.appendChild(el('h3',null,(qftStage+1)+'. '+s.title));body.appendChild(el('p',null,s.role));const question=el('div','qft-think');question.appendChild(el('span','review-kicker','교사의 생각을 여는 질문'));question.appendChild(el('p',null,s.think));body.appendChild(question);
 const pair=el('div','qft-guide-pair');for(const [label,text] of [['학생에게 맡길 일',s.student],['자료로 옮길 때',s.material]]){const c=el('div');c.appendChild(el('strong',null,label));c.appendChild(el('p',null,text));pair.appendChild(c);}body.appendChild(pair);const choice=el('details','method-sources');choice.appendChild(el('summary',null,'결정이 어려울 때 살펴볼 관점'));choice.appendChild(el('p',null,s.choose));body.appendChild(choice);body.appendChild(el('p','src','MD에 남길 내 생각: '+s.blank));p.appendChild(body);
 const more=el('details','qft-md-preview');more.appendChild(el('summary',null,'내려받을 MD 내용 미리보기'));more.appendChild(el('pre',null,qftDesignMd(r)));p.appendChild(more);
 const source=el('details','method-sources');source.appendChild(el('summary',null,'QFT 출처와 안내'));source.appendChild(el('p','src',QFT_CREDIT));const a=el('a',null,'RQI 공식 QFT 안내');a.href='https://rightquestion.org/what-is-the-qft/';a.target='_blank';a.rel='noopener';source.appendChild(a);source.appendChild(el('p','src','QFT를 참고한 한국어 설계 도움자료이며 공식 번역본이 아닙니다.'));p.appendChild(source);
 // Retain a recovery path for previously saved records without making recording the workflow.
 let prior=null;try{const x=JSON.parse(localStorage.getItem('qft-v1-'+r.c)||'null');if(qftValid(x,r.c))prior=x;}catch(e){}
 if(prior){const old=el('details','method-sources');old.appendChild(el('summary',null,'이전 버전에서 저장한 질문 기록 보관'));old.appendChild(el('p','src','이전에 입력한 기록은 유지되어 있습니다. 아래에서 파일로 보관할 수 있습니다.'));const b=el('button','btn','이전 질문 기록 내려받기');b.onclick=()=>download('학생질문_'+r.c+'.json',JSON.stringify(prior,null,2),'application/json');old.appendChild(b);p.appendChild(old);}
};
