/* Small per-standard data, shared UI and export. No inference API at runtime. */
const PILOT_DESIGNS=__PILOT_DESIGNS__;
const PILOT_SOURCES=__PILOT_SOURCES__;
const pilotOf=r=>PILOT_DESIGNS.find(x=>x.code===r.c);
const pilotSource=r=>PILOT_SOURCES.records.find(x=>x.code===r.c);
const beforePilotSource=reviewSourceText;
reviewSourceText=function(r){const s=pilotSource(r);return s?s.file+' · PDF '+s.pages.join(', ')+'쪽 (PDF 파일의 페이지 번호)'+(s.notationNote?'\n원문 표기 참고: '+s.notationNote:''):beforePilotSource(r);};
function pilotText(r){const x=pilotOf(r);if(!x)return '';return '## 기준별 설계 도움 · AI 초안 / 교사가 검토할 제안\n\n'+x.title+'\n\n'+[['facts','사실·사례를 고르는 관점'],['relation','검토할 관계 가설'],['think','교사의 생각을 여는 질문'],['focus','QFT 질문 초점의 자료 후보'],['evidence','살펴볼 학습 증거'],['feedback','증거를 보고 되돌려 줄 도움'],['transfer','새 상황에 적용하기'],['boundary','설계할 때 지킬 범위']].map(([k,l])=>'### '+l+'\n'+x[k]).join('\n\n')+'\n\n개념 후보: '+x.concepts.join(' · ')+'\n\n내가 선택하거나 바꿀 부분과 이유: ______\n\n질문 초점의 자료 후보는 교사용 참고입니다. 학생이 만들어야 할 질문이나 도달할 정답을 미리 채우지 마세요.\n';}
function pilotCard(r){const x=pilotOf(r),s=pilotSource(r),box=el('section','pilot-card');box.appendChild(el('div','review-kicker','10개 교과 시범 · 기준별 설계 도움'));box.appendChild(el('h3',null,x.title));box.appendChild(el('p','src','AI가 작성한 검토용 제안입니다. 교과서와 우리 반 맥락에 맞게 선택·수정하세요.'));
 const rail=el('div','inquiry-rail'),detail=el('div','inquiry-explanation');detail.setAttribute('aria-live','polite');const steps=[['사실·사례',x.facts],['개념 후보',x.concepts.join(' · ')],['관계 가설',x.relation],['전이',x.transfer]];
 steps.forEach(([label,text],i)=>{const b=el('button','inquiry-stage'+(!i?' active':''));b.setAttribute('aria-pressed',String(!i));b.appendChild(el('strong',null,label));b.onclick=()=>{rail.querySelectorAll('button').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',String(n===b));});detail.textContent=text;};rail.appendChild(b);});detail.textContent=steps[0][1];box.append(rail,detail);const think=el('div','qft-think');think.appendChild(el('span','review-kicker','교사의 생각을 여는 질문'));think.appendChild(el('p',null,x.think));box.appendChild(think);
 for(const [label,text] of [['질문 초점의 자료를 고를 때',x.focus],['학습 증거와 피드백',x.evidence+'\n\n'+x.feedback],['설계 범위 확인',x.boundary]]){const d=el('details','method-sources');d.appendChild(el('summary',null,label));d.appendChild(el('p','review-linked',text));box.appendChild(d);}
 const src=el('details','method-sources');src.appendChild(el('summary',null,'공식 원문과 대조한 위치'));const a=el('p');reviewLink(a,'교육과정 PDF '+s.pages.join(', ')+'쪽',s.file,s.pages[0]);src.appendChild(a);const l=el('p');reviewLink(l,'성취수준 PDF '+(r.c==='[4체01-05]'?'139–140':s.levelPages.join(', '))+'쪽',s.levelFile,s.levelPages[0]);src.appendChild(l);src.appendChild(el('p','src','코드·문장과 A/B/C를 공백·기호 이형을 구분하여 대조했습니다. 공식 영역의 연결 전체를 검증한 것은 아닙니다.'));if(s.notationNote)src.appendChild(el('p','src',s.notationNote));box.appendChild(src);return box;
}
const beforePilotQft=qftPane;
qftPane=function(p,r){beforePilotQft(p,r);if(pilotOf(r)){const card=pilotCard(r);p.querySelector('.qft-package').after(card);}};
const beforePilotMd=qftDesignMd;
qftDesignMd=function(r){const s=pilotSource(r);if(!s)return beforePilotMd(r);const exact=r.c==='[4체01-05]'?{...r,...Object.fromEntries(['A','B','C'].map(k=>[k,r[k].replaceAll('·','ㆍ')]))}:r;let md=beforePilotMd(exact);md=md.replace('출처: 앱의 성취수준 자료. 항목별 공식 문서·쪽은 교사가 확인해 기록: ______','출처: '+s.levelFile+' · PDF '+(r.c==='[4체01-05]'?'139–140':s.levelPages.join(', '))+'쪽');return md.replace('## 2. 교사가 먼저 생각해 볼 것',pilotText(r)+'\n## 2. 교사가 먼저 생각해 볼 것');};
const beforePilotPlan=panePlan;
panePlan=function(p,r,t){if(inquiryMode!=='teacher'||!pilotOf(r)||isReviewSample(r))return beforePilotPlan(p,r,t);const modes=el('div','qft-mode');for(const [k,l] of [['student','학생 질문에서 시작'],['teacher','교사 설계·예시']]){const b=el('button','btn'+(inquiryMode===k?' on':''),l);b.setAttribute('aria-pressed',String(inquiryMode===k));b.onclick=()=>{inquiryMode=k;renderDetail();};modes.appendChild(b);}p.appendChild(modes);p.appendChild(pilotCard(r));p.appendChild(el('p','src','예시를 읽고 선택한 방향은 QFT 설계 MD의 빈칸에 적거나 AI와 대화하며 구체화하세요.'));const b=el('button','btn on','QFT 설계 MD 내려받기');b.onclick=()=>download('QFT_설계노트_'+r.c.replace(/[\[\]]/g,'')+'.md',qftDesignMd(r),'text/markdown;charset=utf-8');p.appendChild(b);};
const beforePilotMap=paneMap;
paneMap=function(p,r){const x=pilotOf(r);if(!x||isReviewSample(r))return beforePilotMap(p,r);p.appendChild(el('h3',null,'개념 사이의 관계를 검토하기'));p.appendChild(el('p','src','아래 연결은 교사의 탐구 설계를 돕는 AI 가설입니다. 공식 교육과정 위계나 검증된 인과 모형을 뜻하지 않습니다.'));const flow=el('div','pilot-map');x.concepts.forEach((c,i)=>{flow.appendChild(el('div','review-node',c));if(i<x.concepts.length-1)flow.appendChild(el('span','pilot-map-edge','↔'));});p.appendChild(flow);p.appendChild(el('p','review-evidence',x.relation));const b=el('button','btn','이 관계를 살펴볼 증거와 적용 범위');const detail=el('div','review-evidence');detail.hidden=true;detail.appendChild(el('p',null,x.evidence));detail.appendChild(el('p',null,x.boundary));b.setAttribute('aria-expanded','false');b.onclick=()=>{detail.hidden=!detail.hidden;b.setAttribute('aria-expanded',String(!detail.hidden));};p.append(b,detail);};
const beforePilotStart=startReview;
startReview=function(){beforePilotStart();const banner=document.querySelector('.review-banner');if(!banner)return;const l=el('label','pilot-picker','시범 사례 '),select=el('select');select.setAttribute('aria-label','10개 교과 시범 사례');PILOT_DESIGNS.forEach(x=>{const s=pilotSource({c:x.code}),o=el('option',null,s.subject+' '+x.code);o.value=x.code;select.appendChild(o);});select.value=REVIEW_CODE;select.onchange=()=>{const r=STD.find(x=>x.c===select.value);S.q='';$('#q').value='';S.bands.clear();S.subjs.clear();S.areas.clear();S.bands.add(r.b);S.subjs.add(r.s);S.sel=r;S.tab='plan';S.map=null;inquiryMode='student';qftStage=0;renderFilters();render();$('#detailcol').classList.add('open');};l.appendChild(select);banner.appendChild(l);};
